sdzblog_accueil:
    path:      /
    defaults:  { _controller: SdzBlogBundle:Blog:index }

sdzblog_voir:
    path:      /article/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:voir }

sdzblog_ajouter:
    path:      /ajouter
    defaults:  { _controller: SdzBlogBundle:Blog:ajouter }
